Repository bazelbuild/rules_nodejs, pull requests merged in 2019-10, with the labels that each got.

#1225 test: examples/angular ts_devserver does not need to included @ngrx/store/bundles/store.umd.min.js
  examples/angular/src/BUILD.bazel
Labels: cla: yes

#1222 chore: fix issue in clean_nested_workspaces.sh script
  scripts/clean_nested_workspaces.sh
Labels: cla: yes

#1226 feat(examples): updated to angular 8.2.8 in examples/angular
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+8.2.8.patch
  examples/angular/yarn.lock
Labels: cla: yes

#1224 test: add run_integration_test_debug package.json script to run integration test with DEBUG=1
  package.json
Labels: cla: yes

#1227 feat(examples): upgrade to v9 and enable ivy
  examples/angular/.bazelrc
  examples/angular/angular-metadata.tsconfig.json
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
  examples/angular/src/app/app-routing.module.ts
  examples/angular/src/main.dev.ts
  examples/angular/src/main.prod.ts
  examples/angular/yarn.lock
Labels: cla: yes

#1211 fix(docs): fix typo in TypeScript.md
  docs/TypeScript.md
  packages/typescript/docs/install.md
Labels: cla: yes

#1205 fix: invalidate installed npm repositories correctly (#1200)
  internal/copy_repository/copy_repository.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/npm_install.bzl
Labels: cla: yes

#1210 fix(README): update "sections below" reference
  README.md
Labels: cla: yes

#1207 fix(builtin): bugs in 0.38 found while rolling out to angular repo
  internal/linker/link_node_modules.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/test/BUILD.bazel
  internal/npm_install/test/generate_build_file.spec.js
Labels: cla: yes

#1233 fix: clean_nested_workspaces.sh
  scripts/clean_nested_workspaces.sh
Labels: cla: yes

#1235 refactor: remove //internal:collect_es6_sources.bzl which re-exports collect_es6_sources()
  internal/collect_es6_sources.bzl
Labels: cla: yes

#1232 chore: fix comment in WORKSPACE for local development
  WORKSPACE
Labels: cla: yes

#1239 test(protractor): use new rollup_bundle in protractor-2 test
  packages/protractor/test/protractor-2/BUILD.bazel
Labels: cla: yes

#1238 feat(examples): update examples/angular to new rollup_bundle
  examples/BUILD.bazel
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
  examples/angular/src/BUILD.bazel
  examples/angular/src/example/BUILD.bazel
  examples/angular/src/example/index.dev.html
  examples/angular/src/example/index.html
  examples/angular/src/lib/shorten/BUILD.bazel
  examples/angular/src/lib/shorten/index.ts
  examples/angular/src/rollup.config.js
  examples/angular/yarn.lock
Labels: cla: yes

#1234 refactor: switch collect_es6_sources to use JSEcmaScriptModuleInfo
  internal/common/collect_es6_sources.bzl
Labels: cla: yes

#1242 feat(typescript): add direct_sources field to JSEcmaScriptModuleInfo
  examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
  packages/typescript/src/internal/build_defs.bzl
  providers.bzl
Labels: cla: yes

#1229 feat(examples): add closure compiler example
  examples/BUILD.bazel
  examples/closure/.bazelignore
  examples/closure/.bazelrc
  examples/closure/BUILD.bazel
  examples/closure/WORKSPACE
  examples/closure/hello.js
  examples/closure/package.json
  examples/closure/test.js
  examples/closure/yarn.lock
  examples/index.bzl
  package.json
  yarn.lock
Labels: cla: yes

#1243 feat(typescript): add a transitive_js_ecma_script_module_info alias to js_ecma_script_module_info
  examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
  providers.bzl
Labels: cla: yes

#1231 refactor: e2e and examples no longer nested workspaces
  .bazelrc
  WORKSPACE
  e2e/BUILD.bazel
  e2e/bazel_managed_deps/BUILD.bazel
  e2e/fine_grained_symlinks/BUILD.bazel
  e2e/index.bzl
  e2e/jasmine/BUILD.bazel
  e2e/karma/BUILD.bazel
  e2e/karma_stack_trace/BUILD.bazel
  e2e/karma_stack_trace/test_folder/BUILD.bazel
  e2e/karma_typescript/BUILD.bazel
  e2e/node_loader_no_preserve_symlinks/BUILD.bazel
  e2e/node_loader_preserve_symlinks/BUILD.bazel
  e2e/symlinked_node_modules_npm/BUILD
  e2e/symlinked_node_modules_yarn/BUILD
  e2e/test.bzl
  e2e/ts_auto_deps/BUILD.bazel
  e2e/ts_devserver/BUILD.bazel
  e2e/ts_devserver/genrule/BUILD.bazel
  e2e/ts_devserver/subpackage/BUILD.bazel
  e2e/typescript/BUILD.bazel
  e2e/webapp/BUILD.bazel
  e2e/webpack/BUILD.bazel
  examples/BUILD.bazel
  examples/angular/BUILD.bazel
  examples/angular/e2e/BUILD.bazel
  examples/angular/src/BUILD.bazel
  examples/angular/src/app/BUILD.bazel
  examples/angular/src/app/hello-world/BUILD.bazel
  examples/angular/src/app/home/BUILD.bazel
  examples/angular/src/app/todos/BUILD.bazel
  examples/angular/src/app/todos/reducers/BUILD.bazel
  examples/angular/src/assets/BUILD.bazel
  examples/angular/src/example/BUILD.bazel
  examples/angular/src/lib/shorten/BUILD.bazel
  examples/angular/src/shared/material/BUILD.bazel
  examples/angular/tools/BUILD.bazel
  examples/app/BUILD.bazel
  examples/app/styles/BUILD.bazel
  examples/app/test/BUILD.bazel
  examples/closure/BUILD.bazel
  examples/index.bzl
  examples/kotlin/BUILD.bazel
  examples/nestjs/BUILD.bazel
  examples/nestjs/src/BUILD.bazel
  examples/parcel/BUILD.bazel
  examples/protocol_buffers/BUILD.bazel
  examples/test.bzl
  examples/user_managed_deps/BUILD.bazel
  examples/vendored_node/BUILD.bazel
  examples/vendored_node_and_yarn/BUILD.bazel
  examples/web_testing/BUILD.bazel
  examples/webapp/BUILD.bazel
  examples/worker/BUILD.bazel
  internal/bazel_integration_test/bazel_integration_test.bzl
  internal/bazel_integration_test/test_runner.js
  package.json
  yarn.lock
Labels: cla: yes

#1246 chore: remove sourcemap from checked in ts
  internal/linker/index.js
  internal/npm_install/generate_build_file.js
  packages/typescript/src/index.from_src.bzl
Labels: cla: yes

#1247 feat: document the escape hatch from ts_library
  examples/app/BUILD.bazel
  examples/app/package.json
  examples/app/tsconfig-test.json
  examples/app/yarn.lock
  internal/node/npm_package_bin.bzl
  packages/typescript/docs/install.md
Labels: cla: yes

#1216 mocha_test example
  examples/BUILD.bazel
  examples/webapp/BUILD.bazel
  examples/webapp/package.json
  examples/webapp/sourcemaps.spec.js
  examples/webapp/yarn.lock
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/test/golden/@gregmagolan/test-a/index.bzl.golden
  internal/npm_install/test/golden/jasmine/index.bzl.golden
Labels: cla: yes

#1251 Slack channel is #javascript
  docs/_includes/drawer.html
Labels: cla: yes

#1215 feat(typescript): add JSNamedModuleInfo provider to ts_library outputs
  WORKSPACE
  examples/angular/patches/@angular+bazel+9.0.0-next.8.patch
  internal/common/devmode_js_sources.bzl
  internal/common/node_module_info.bzl
  internal/common/npm_package_info.bzl
  internal/common/sources_aspect.bzl
  internal/linker/link_node_modules.bzl
  internal/node.bzl
  internal/node/node.bzl
  internal/node/npm_package_bin.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/node_module_library.bzl
  internal/npm_install/npm_umd_bundle.bzl
  internal/npm_install/test/golden/@angular/core/BUILD.bazel.golden
  internal/npm_package/npm_package.bzl
  internal/rollup/rollup_bundle.bzl
  packages/jasmine/docs/BUILD.bazel
  packages/karma/docs/BUILD.bazel
  packages/karma/src/karma_web_test.bzl
  packages/karma/src/web_test.bzl
  packages/labs/src/protobufjs/ts_proto_library.bzl
  packages/protractor/docs/BUILD.bazel
  packages/protractor/src/protractor_web_test.bzl
  packages/rollup/src/rollup_bundle.bzl
  packages/typescript/src/internal/build_defs.bzl
  packages/typescript/src/internal/devserver/ts_devserver.bzl
  packages/typescript/test/devmode_consumer/devmode_consumer.bzl
  providers.bzl
Labels: cla: yes

#1111 fix: dont generate build files in symlinked node_modules
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
Labels: cla: yes

#1256 chore: cleanup workspace now that //:all_files target no longer needed for bazel-in-bazel
  WORKSPACE
  examples/BUILD.bazel
  examples/angular/WORKSPACE
  examples/angular/src/BUILD.bazel
  tools/mock_npm_angular_bazel/BUILD.bazel
  tools/mock_npm_angular_bazel/WORKSPACE
  tools/mock_npm_angular_bazel/index.bzl
  tools/mock_rules_kotlin/README.md
  tools/mock_rules_kotlin/WORKSPACE
  tools/mock_rules_kotlin/kotlin/BUILD.bazel
  tools/mock_rules_kotlin/kotlin/kotlin.bzl
Labels: cla: yes

#1258 chore: use browser_repositories from io_bazel_rules_webtesting in examples/angular
  examples/angular/WORKSPACE
Labels: cla: yes

#1259 chore: update angular examples to 9.0.0-next.10
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-next.10.patch
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/patches/@angular+bazel+9.0.0-next.10.patch
  examples/angular_view_engine/yarn.lock
Labels: cla: yes

#1250 feat(terser): support .map files in directory inputs
  packages/terser/src/index.js
  packages/terser/test/BUILD.bazel
  packages/terser/test/directory-args.spec.js
  packages/terser/test/directory_input/BUILD.bazel
  packages/terser/test/sourcemap/BUILD.bazel
  packages/terser/test/sourcemap/directory_spec.js
  tools/declare_directory.bzl
Labels: cla: yes

#1264 fix(terser): terser_minified should support .mjs files when running on directory
  packages/terser/src/index.js
Labels: cla: yes

#1262 docs: add instructions for multiple sets of npm deps
  docs/install.md
Labels: cla: yes

#1266 chore: scale up the monorepo with generated CODEOWNERS
  .github/BUILD.bazel
  .github/CODEOWNERS
  BUILD.bazel
  CODEOWNERS
  examples/BUILD.bazel
  examples/test.bzl
  index.bzl
  package.bzl
  package.json
  scripts/update_codeowners.sh
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes

#1267 chore: deprecate old rollup_bundle rule
  internal/rollup/rollup_bundle.bzl
  internal/rollup/test/BUILD.bazel
  internal/rollup/test/check.js
  internal/rollup/test/rollup/BUILD.bazel
  internal/rollup/test/rollup/bar.js
  internal/rollup/test/rollup/bundle-cjs_golden.js_
  internal/rollup/test/rollup/bundle-es5umd_golden.js_
  internal/rollup/test/rollup/bundle-min-debug_golden.js_
  internal/rollup/test/rollup/bundle-min-es5umd_golden.js_
  internal/rollup/test/rollup/bundle-min_golden.js.map
  internal/rollup/test/rollup/bundle-min_golden.js_
  internal/rollup/test/rollup/bundle-umd_golden.js_
  internal/rollup/test/rollup/foo.js
  internal/rollup/test/rollup/fum/BUILD.bazel
  internal/rollup/test/rollup/fum/index.js
  internal/rollup/test/rollup/license.txt
  internal/rollup/test/rollup/outputgroups.spec.js
  internal/rollup/test/rollup/rollup.spec.js
  internal/rollup/test/rollup_code_splitting/BUILD.bazel
  internal/rollup/test/rollup_code_splitting/additional_entry.js
  internal/rollup/test/rollup_code_splitting/additional_entry.spec.js
  internal/rollup/test/rollup_code_splitting/code_splitting.spec.js
  internal/rollup/test/rollup_code_splitting/dep1.js
  internal/rollup/test/rollup_code_splitting/dep2.js
  internal/rollup/test/rollup_code_splitting/dep3.js
  internal/rollup/test/rollup_code_splitting/dep4.js
  internal/rollup/test/rollup_code_splitting/dynamic.js
  internal/rollup/test/rollup_code_splitting/goldens/bundle.min.es2015.js_
  internal/rollup/test/rollup_code_splitting/goldens/bundle.min.js_
  internal/rollup/test/rollup_code_splitting/goldens/bundle_multi_entry.min.js_
  internal/rollup/test/rollup_code_splitting/lib1.js
  internal/rollup/test/rollup_code_splitting/lib2.js
  internal/rollup/test/rollup_code_splitting/license.txt
  internal/rollup/test/rollup_code_splitting/main1.js
  internal/rollup/test/rollup_code_splitting/main1.spec.js
  internal/rollup/test/rollup_code_splitting/outputgroups.spec.js
  internal/rollup/test/rollup_fine_grained_deps/BUILD.bazel
  internal/rollup/test/rollup_fine_grained_deps/check.js
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle.es2015.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle.min.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle.min_debug.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_hybrid.es2015.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_hybrid.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_hybrid.min.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_hybrid.min_debug.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_legacy.es2015.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_legacy.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_legacy.min.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_legacy.min_debug.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_no_deps.es2015.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_no_deps.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_no_deps.min.js.golden
  internal/rollup/test/rollup_fine_grained_deps/golden/bundle_no_deps.min_debug.js.golden
  internal/rollup/test/rollup_fine_grained_deps/has-deps.js
  internal/rollup/test/rollup_fine_grained_deps/no-deps.js
  internal/rollup/test/rollup_fine_grained_deps/rollup.spec.js
  internal/rollup/test/rollup_fine_grained_deps/update_golden.js
Labels: cla: yes

#1271 chore: update to latest @angular/bazel 9.0.0-next.10 snapshot build & remove @angular/bazel patches
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-next.10.patch
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/patches/@angular+bazel+9.0.0-next.10.patch
  examples/angular_view_engine/yarn.lock
Labels: cla: yes, cleanup

#1275 docs: add new rollup_bundle and terser_minified rules to docs nav
  docs/_includes/drawer.html
Labels: cla: yes

#1163 Add ability to ignore peer depdenencies from package.json
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
Labels: cla: yes

#1287 refactor: use deps declared on rollup_bundle
  examples/angular/src/BUILD.bazel
  examples/angular_view_engine/src/BUILD.bazel
  examples/kotlin/BUILD.bazel
  internal/linker/link_node_modules.bzl
  internal/node/bazel_require_script.js
  internal/node/node.bzl
  internal/node/node_launcher.sh
  internal/node/npm_package_bin.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/test/generate_build_file.spec.js
  internal/providers/node_runtime_deps_info.bzl
  packages/rollup/src/rollup_bundle.bzl
  packages/rollup/test/integration/BUILD.bazel
  packages/rollup/test/plugins/BUILD.bazel
  providers.bzl
Labels: cla: yes

#1276 refactor: remove dynamic_deps feature
  WORKSPACE
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/npm_install.bzl
  internal/npm_install/test/generate_build_file.spec.js
  internal/npm_install/test/golden/@gregmagolan/test-a/bin/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-a/index.bzl.golden
  internal/npm_install/test/golden/jasmine/bin/BUILD.bazel.golden
  internal/npm_install/test/golden/jasmine/index.bzl.golden
  packages/typescript/docs/install.md
Labels: cla: yes

#1274 feat(examples): add Jest example
  .bazelrc
  examples/BUILD.bazel
  examples/jest/.bazelignore
  examples/jest/.bazelrc
  examples/jest/BUILD.bazel
  examples/jest/README.md
  examples/jest/WORKSPACE
  examples/jest/babel.config.js
  examples/jest/dummy_test.sh
  examples/jest/extra.js
  examples/jest/index.js
  examples/jest/index.test.js
  examples/jest/index2.test.js
  examples/jest/jest.bzl
  examples/jest/jest.config.js
  examples/jest/package.json
  examples/jest/tools/BUILD.bazel
  examples/jest/tools/patches/@jest+core+24.7.1.patch
  examples/jest/tools/patches/@jest+transform+24.7.1.patch
  examples/jest/tools/patches/babel-plugin-istanbul+5.1.2.patch
  examples/jest/tools/patches/istanbul-api+2.1.5.patch
  examples/jest/tools/patches/jest-cli+24.7.1.patch
  examples/jest/tools/patches/jest-config+24.7.1.patch
  examples/jest/tools/patches/jest-haste-map+24.7.1.patch
  examples/jest/tools/patches/jest-resolve+24.7.1.patch
  examples/jest/tools/patches/jest-runtime+24.7.1.patch
  examples/jest/yarn.lock
Labels: cla: yes

#1268 chore(examples): upgrade ruels_docker
  examples/angular/WORKSPACE
Labels: cla: yes

#1281 fix(builtin): allow more than 2 segments in linker module names
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/linker/test/link_node_modules.spec.ts
  packages/rollup/test/integration/BUILD.bazel
  packages/rollup/test/integration/far/a/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/index.ts
  packages/rollup/test/integration/far/a/index.ts
  packages/rollup/test/integration/foo.js
  packages/rollup/test/integration/foo/BUILD.bazel
  packages/rollup/test/integration/foo_a/BUILD.bazel
  packages/rollup/test/integration/foo_a/index.ts
  packages/rollup/test/integration/foo_aaa/BUILD.bazel
  packages/rollup/test/integration/foo_aaa/index.ts
  packages/rollup/test/integration/fum/BUILD.bazel
  packages/rollup/test/integration/golden.amd.js_
  packages/rollup/test/integration/golden.cjs.js_
  packages/rollup/test/integration/golden.esm.js_
  packages/rollup/test/integration/golden.iife.js_
  packages/rollup/test/integration/golden.system.js_
  packages/rollup/test/integration/golden.umd.js_
  packages/rollup/test/integration/golden.umd.sha256_
Labels: cla: yes, enhancement, package:builtin

#1291 fix: webpack should be a peerDep of @bazel/labs
  e2e/webpack/package.json
  e2e/webpack/yarn.lock
  packages/labs/src/package.json
  packages/rollup/src/package.json
  packages/terser/src/package.json
Labels: bug, cla: yes

#1295 chore: update renovate to extend from new config:js-app
  renovate.json
Labels: cla: yes

#1297 chore: cleanup unneeded io_bazel dep
  package.bzl
Labels: cla: yes

#1310 fix(karma): load scripts in strict mode
  packages/karma/src/index.ts
Labels: cla: yes

#1255 feat(examples): demonstrate using Webpack to build and serve a React app
  .bazelrc
  examples/BUILD.bazel
  examples/react_webpack/.bazelignore
  examples/react_webpack/.bazelrc
  examples/react_webpack/BUILD.bazel
  examples/react_webpack/README.md
  examples/react_webpack/WORKSPACE
  examples/react_webpack/index.html
  examples/react_webpack/index.tsx
  examples/react_webpack/package.json
  examples/react_webpack/styles.scss
  examples/react_webpack/types.d.ts
  examples/react_webpack/webpack.config.js
  examples/react_webpack/yarn.lock
Labels: cla: yes

#1302 chore: update bazel-toolchains
  examples/angular/WORKSPACE
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_view_engine/WORKSPACE
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  package.bzl
Labels: cla: yes

#1313 chore: update NodeJS to LTS 12.13.0 and yarn to 1.19.1 version
  examples/angular/package.json
  examples/angular_view_engine/package.json
  internal/node/node_repositories.bzl
  packages/jasmine/test/templated_args_test.js
  packages/labs/src/protobufjs/package.json
  packages/labs/src/protobufjs/yarn.lock
Labels: cla: yes
