Repository bazelbuild/rules_nodejs, pull requests merged in 2020-04, with the labels that each got.

#1773 build: ts_project windows ci fix
  packages/rollup/test/integration/far/a/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/BUILD.bazel
  packages/rollup/test/integration/far/a/tsconfig.json
Labels: cla: yes

#1772 fix(builtin): preserve lone $ in templated_args for legacy support
  internal/common/preserve_legacy_templated_args.bzl
  internal/common/test/BUILD.bazel
  internal/common/test/preserve_legacy_rlocation_test.bzl
  internal/common/test/preserve_legacy_templated_args_test.bzl
  internal/node/node.bzl
  internal/node/test/BUILD.bazel
Labels: cla: yes, package:builtin

#1774 ci: shard all integration tests
  .circleci/config.yml
  scripts/ci/run_integration_tests.sh
Labels: cla: yes

#1798 chore: cleanup $(rlocation) uses and comments
  examples/angular/src/BUILD.bazel
  examples/angular_view_engine/src/BUILD.bazel
  internal/node/test/BUILD.bazel
Labels: cla: yes

#1799 refactor(builtin): cleanup and optimizations in nodejs_binary & linker
  internal/linker/BUILD.bazel
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/node/node.bzl
  third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
Labels: cla: yes, package:builtin

#1802 fix(builtin): fix npm_version_check.js when running outside of bazel
  internal/npm_version_check.js
Labels: cla: yes

#1810 ci: bump to circleci:node:12.14-browsers
  .circleci/config.yml
Labels: cla: yes

#1808 refactor: cleanup examples/parcel spec to use runfiles helper instead of absolute require
  examples/parcel/parcel.spec.js
Labels: cla: yes

#1805 fix(builtin): always symlink node_modules at `execroot/my_wksp/node_modules` even when running in runfiles
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/linker/test/link_node_modules.spec.ts
  internal/node/node.bzl
  third_party/github.com/bazelbuild/bazel/tools/bash/runfiles/runfiles.bash
Labels: cla: yes

#1792 fix(rollup): fix worker not picking up config file changes
  packages/rollup/src/index.js
Labels: cla: yes

#1811 chore: remove typescript index.from_src
  internal/linker/BUILD.bazel
  internal/linker/index.js
  internal/linker/test/integration/run_program.sh
  internal/npm_install/BUILD.bazel
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/index.js
  internal/npm_install/npm_install.bzl
  internal/npm_install/test/package/BUILD.bazel
  packages/protractor/test/protractor-2/BUILD.bazel
  packages/typescript/src/checked_in_ts_project.bzl
  packages/typescript/src/index.from_src.bzl
  packages/typescript/src/internal/ts_project.bzl
  tools/mock_npm_bazel_typescript/checked_in_ts_project.bzl
Labels: cla: yes

#1814 test(builtin): add test for issue 1813
  internal/linker/test/issue_1813/BUILD.bazel
  internal/linker/test/issue_1813/index.test.js
  internal/linker/test/issue_1813/jest.config.js
  package.json
  patches/jest-haste-map+25.3.0.patch
  yarn.lock
Labels: cla: yes

#1815 ci: increase no_output_timeout to 30m for integration job
  .circleci/config.yml
  scripts/ci/run_integration_tests.sh
Labels: cla: yes

#1800 fix(builtin): don't allow symlinks to escape or enter bazel managed node_module folders
  internal/node/BUILD.bazel
  internal/node/launcher.sh
  internal/node/node.bzl
  internal/node/node_patches.js
  internal/node/test/BUILD.bazel
  internal/node/test/dump_build_env.js
  internal/node/test/env.spec.js
  internal/providers/node_runtime_deps_info.bzl
  packages/node-patches/register.ts
  packages/node-patches/src/fs.ts
  packages/node-patches/test/fs/escape.ts
  packages/node-patches/test/fs/lstat.ts
  packages/node-patches/test/fs/opendir.ts
  packages/node-patches/test/fs/readdir.ts
  packages/node-patches/test/fs/readlink.ts
  packages/node-patches/test/fs/realpath.ts
Labels: cla: yes, package:builtin

#1794 chore: update to bazel 3.0 final
  .bazelci/presubmit.yml
  .bazelversion
  index.bzl
Labels: cla: yes

#1795 fix(npm_umd_bundle): include all json files
  internal/npm_install/npm_umd_bundle.bzl
Labels: cla: yes

#1818 fix(builtin): fix node patches lstat short-circuit logic
  internal/node/node_patches.js
  packages/node-patches/src/fs.ts
Labels: cla: yes

#1816 fix(builtin): look in the execroot for nodejs_binary source entry_points
  internal/node/launcher.sh
  internal/node/node.bzl
Labels: cla: yes

#1825 chore: add bazel-out and dist folders to bazelignore
  e2e/jasmine/.bazelignore
  examples/angular/.bazelignore
  examples/angular_bazel_architect/.bazelignore
  examples/angular_view_engine/.bazelignore
  examples/app/.bazelignore
  examples/closure/.bazelignore
  examples/jest/.bazelignore
  examples/nestjs/.bazelignore
  examples/parcel/.bazelignore
  examples/protocol_buffers/.bazelignore
  examples/react_webpack/.bazelignore
  examples/vendored_node/.bazelignore
  examples/vendored_node_and_yarn/.bazelignore
  examples/web_testing/.bazelignore
  examples/webapp/.bazelignore
  packages/create/index.js
Labels: cla: yes

#1824 Docs: Add mandatory argument to `npm init @bazel`
  README.md
Labels: cla: yes, question/docs

#1496 feat(examples): upgrade rules_docker to 0.13.0
  .circleci/bazel.rc
  examples/BUILD.bazel
  examples/angular/WORKSPACE
  examples/angular/rules_docker.patch
  examples/angular/src/BUILD.bazel
  examples/nestjs/WORKSPACE
  examples/nestjs/rules_docker.patch
  examples/nestjs/src/BUILD.bazel
  internal/bazel_integration_test/test_runner.js
Labels: cla: yes

#1828 Follow-on tweaks to README
  README.md
Labels: cla: yes

#1835 fix(builtin): fix linker issue when running test with "local" tag on osx & linux
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/linker/test/local/BUILD.bazel
  internal/linker/test/local/fit/BUILD.bazel
  internal/linker/test/local/fit/main.ts
  internal/linker/test/local/fit/package.json
  internal/linker/test/local/fit/tsconfig.json
  internal/linker/test/local/test.js
Labels: cla: yes

#1837 chore: update to bazelisk 1.4
  docs/install.md
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_bazel_architect/package.json
  examples/angular_bazel_architect/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  examples/nestjs/package.json
  examples/nestjs/yarn.lock
  examples/react_webpack/package.json
  examples/react_webpack/yarn.lock
  package.json
  packages/create/index.js
  scripts/publish_release.sh
  scripts/update_codeowners.sh
  yarn.lock
Labels: cla: yes

#1839 feat(examples): show how to use ts_library(use_angular_plugin) with w…
  .bazelrc
  examples/angular/src/BUILD.bazel
  examples/angular/src/app/BUILD.bazel
  examples/angular/src/app/hello-world/BUILD.bazel
  examples/angular/src/app/home/BUILD.bazel
  examples/angular/src/app/todos/BUILD.bazel
  examples/angular/src/shared/material/BUILD.bazel
  examples/angular/tools/BUILD.bazel
  examples/angular/tools/angular_ts_library.bzl
  packages/typescript/src/internal/build_defs.bzl
Labels: cla: yes
