Repository bazelbuild/rules_nodejs, pull requests merged in 2020-08, with the labels that each got.

#2088 chore: upgrade rollup to ^2.3.0
  e2e/webapp/package.json
  e2e/webapp/yarn.lock
  examples/angular/package.json
  examples/angular/src/BUILD.bazel
  examples/angular/src/rollup.config.js
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/src/BUILD.bazel
  examples/angular_view_engine/src/rollup.config.js
  examples/angular_view_engine/yarn.lock
  examples/from_source/package.json
  examples/kotlin/BUILD.bazel
  examples/kotlin/package-lock.json
  examples/kotlin/package.json
  examples/kotlin/rollup.config.js
  examples/protocol_buffers/BUILD.bazel
  examples/protocol_buffers/package.json
  examples/protocol_buffers/rollup.config.js
  examples/protocol_buffers/yarn.lock
  examples/webapp/package.json
  examples/webapp/yarn.lock
  internal/generated_file_test/BUILD.bazel
  internal/generated_file_test/rollup.config.js
  internal/node/node_patches.js
  package.json
  packages/labs/test/grpc_web/BUILD.bazel
  packages/labs/test/grpc_web/rollup.config.js
  packages/node-patches/BUILD.bazel
  packages/node-patches/rollup.config.js
  packages/rollup/test/code_splitting/spec.js
  packages/rollup/test/integration/BUILD.bazel
  packages/rollup/test/integration/golden.amd.js.map.sha256_
  packages/rollup/test/integration/golden.amd.js_
  packages/rollup/test/integration/golden.cjs.js.map.sha256_
  packages/rollup/test/integration/golden.cjs.js_
  packages/rollup/test/integration/golden.esm.js.map.sha256_
  packages/rollup/test/integration/golden.esm.js_
  packages/rollup/test/integration/golden.iife.js.map.sha256_
  packages/rollup/test/integration/golden.iife.js_
  packages/rollup/test/integration/golden.system.js.map.sha256_
  packages/rollup/test/integration/golden.system.js_
  packages/rollup/test/integration/golden.umd.js.map.sha256_
  packages/rollup/test/integration/golden.umd.js.sha256_
  packages/rollup/test/integration/golden.umd.js_
  packages/rollup/test/integration/rollup.config.js
  packages/rollup/test/plugins/BUILD.bazel
  packages/rollup/test/plugins/rollup.config.js
  yarn.lock
Labels: cla: yes

#2100 fix(builtin): fix coverage lcov merger script jumping out of sandbox and not being able to find c8
  .bazelrc
  e2e/BUILD.bazel
  e2e/coverage/.bazelignore
  e2e/coverage/.bazelrc
  e2e/coverage/BUILD.bazel
  e2e/coverage/WORKSPACE
  e2e/coverage/coverage.spec.js
  e2e/coverage/coverage_source.ts
  e2e/coverage/package.json
  e2e/coverage/tsconfig.json
  e2e/coverage/yarn.lock
  internal/node/launcher.sh
Labels: cla: yes

#2101 docs: use @npm//@bazel for example load sites
  packages/labs/protobufjs/ts_proto_library.bzl
  packages/rollup/rollup_bundle.bzl
  packages/terser/terser_minified.bzl
Labels: cla: yes

#2095 fix(cypress): allow for async cypress plugins
  WORKSPACE
  packages/cypress/BUILD.bazel
  packages/cypress/internal/cypress_repository.bzl
  packages/cypress/internal/install-cypress.js
  packages/cypress/internal/plugins/index.template.js
  packages/cypress/internal/run-cypress.js
  packages/cypress/internal/template.cypress_web_test.bzl
Labels: cla: yes

#2112 feat(example): add targets in angular_bazel_architect for production serve and build
  examples/angular_bazel_architect/BUILD.bazel
Labels: cla: yes, examples

#2113 fix(examples): use ./ prefix on babel config file
  docs/index.md
  examples/webapp/differential_loading.bzl
Labels: cla: yes

#2114 refactor(rollup): use rollup loadConfigFile API
  packages/rollup/index.js
Labels: cla: yes

#2118 fix(typescript): only expect .js outs for .tsx? srcs
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/json/BUILD.bazel
  packages/typescript/test/ts_project/json/baz.svg
Labels: cla: yes

#2109 feat(builtin): new js_library rule
  WORKSPACE
  internal/js_library/js_library.bzl
  internal/node/test/lib2/BUILD.bazel
  internal/npm_install/generate_build_file.ts
  internal/npm_install/index.js
  internal/npm_install/node_module_library.bzl
  internal/npm_install/test/golden/@angular/core/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-a/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-b/BUILD.bazel.golden
  internal/npm_install/test/golden/BUILD.bazel.golden
  internal/npm_install/test/golden/ajv/BUILD.bazel.golden
  internal/npm_install/test/golden/jasmine/BUILD.bazel.golden
  internal/npm_install/test/golden/rxjs/BUILD.bazel.golden
  internal/npm_install/test/golden/unidiff/BUILD.bazel.golden
  internal/npm_install/test/golden/zone.js/BUILD.bazel.golden
  internal/npm_install/test/package/BUILD.bazel
  internal/providers/npm_package_info.bzl
  packages/jasmine/BUILD.bazel
  packages/labs/grpc_web/BUILD.bazel
  packages/rollup/test/integration/far/a/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/BUILD.bazel
  packages/typescript/internal/ts_project.bzl
Labels: cla: yes

#2117 fix(typescript): produce .d.ts as default output rather than empty
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/declaration_only/BUILD.bazel
  packages/typescript/test/ts_project/declaration_only/a.d.ts_
  packages/typescript/test/ts_project/declaration_only/a.ts
  packages/typescript/test/ts_project/declaration_only/tsconfig.json
Labels: cla: yes

#2126 Add NodeJS versions
  internal/node/node_repositories.bzl
  scripts/update-nodejs-versions.js
Labels: cla: no

#2128 refactor: move node version list into its own file
  internal/node/node_repositories.bzl
  internal/node/node_versions.bzl
  package.json
  scripts/update-nodejs-versions.js
Labels: cla: yes

#2138 fix(typescript): add the tsBuildInfoFile option to ts_project
  packages/typescript/internal/ts_project.bzl
  packages/typescript/internal/ts_project_options_validator.ts
  packages/typescript/test/ts_project/tsbuildinfofile/BUILD.bazel
  packages/typescript/test/ts_project/tsbuildinfofile/a.ts
  packages/typescript/test/ts_project/tsbuildinfofile/tsconfig.json
Labels: cla: yes

#2139 Ts config ts project
  packages/typescript/internal/ts_config.bzl
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/BUILD
  packages/typescript/test/ts_project/ts_config/BUILD.bazel
  packages/typescript/test/ts_project/ts_config/a.ts
  packages/typescript/test/ts_project/ts_config/tsconfig-extended.json
  packages/typescript/test/ts_project/ts_config/tsconfig.json
Labels: cla: yes

#2146 docs: minor cleanup of builtins page
  docs/Built-ins.html
  docs/Built-ins.md
  docs/README.md
  docs/TypeScript.html
  docs/TypeScript.md
  internal/node/node_repositories.bzl
  package.json
Labels: cla: yes

#2147 docs: fix spacing and link colours on rhs sidenav
  docs/css/_sidebar.scss
  docs/css/main.css
Labels: cla: yes

#2152 chore: update circleci image to latest to pick up newer chrome
  .circleci/config.yml
Labels: cla: yes

#2151 docs: add search to docsite using gcse
  docs/BUILD.bazel
  docs/Built-ins.html
  docs/Cypress.html
  docs/Jasmine.html
  docs/Karma.html
  docs/Protractor.html
  docs/Rollup.html
  docs/Terser.html
  docs/TypeScript.html
  docs/_includes/footer-content.html
  docs/_includes/header.html
  docs/_includes/sidenav.html
  docs/_layouts/search.html
  docs/changing-rules.html
  docs/debugging.html
  docs/dependencies.html
  docs/examples.html
  docs/index.html
  docs/install.html
  docs/repositories.html
  docs/search.html
  docs/search.md
  docs/stamping.html
  tools/stardoc/jekyll.bzl
Labels: cla: yes

#2130 feat(typescript): generate tsconfig.json for ts_project
  packages/typescript/checked_in_ts_project.bzl
  packages/typescript/internal/ts_config.bzl
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/generated_tsconfig/config/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/config/expected.d.ts.map_
  packages/typescript/test/ts_project/generated_tsconfig/config/expected.d.ts_
  packages/typescript/test/ts_project/generated_tsconfig/config/expected.js.map_
  packages/typescript/test/ts_project/generated_tsconfig/config/expected.js_
  packages/typescript/test/ts_project/generated_tsconfig/config/src/a.ts
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/expected.d.ts.map_
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/expected.d.ts_
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/expected.js.map_
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/expected.js_
  packages/typescript/test/ts_project/generated_tsconfig/config_attrs/src/a.ts
  packages/typescript/test/ts_project/generated_tsconfig/decl_only/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/decl_only/a.ts
  packages/typescript/test/ts_project/generated_tsconfig/decl_only/expected.d.ts_
  packages/typescript/test/ts_project/generated_tsconfig/default/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/default/a.ts
  packages/typescript/test/ts_project/generated_tsconfig/default/expected.js_
  packages/typescript/test/ts_project/generated_tsconfig/extends/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/extends/a.ts
  packages/typescript/test/ts_project/generated_tsconfig/extends/expected.js_
  packages/typescript/test/ts_project/generated_tsconfig/extends/tsconfig-extended.json
  packages/typescript/test/ts_project/generated_tsconfig/gen_src/BUILD.bazel
  packages/typescript/test/ts_project/generated_tsconfig/gen_src/expected.js_
Labels: cla: yes

#2160 docs: document the node_context_data attribute
  internal/pkg_npm/pkg_npm.bzl
  packages/rollup/rollup_bundle.bzl
  providers.bzl
Labels: cla: yes
