Repository bazelbuild/rules_nodejs, pull requests merged in 2020-11, with the labels that each got.

#2251 fix(exmaples/nestjs): add module_name field in ts_library
  examples/nestjs/src/BUILD.bazel
Labels: cla: yes, need: more info

#2266 chore(typescript): remove deprecated extends[]
  examples/app/BUILD.bazel
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/a/BUILD.bazel
  packages/typescript/test/ts_project/b/BUILD.bazel
  packages/typescript/test/ts_project/c/BUILD.bazel
Labels: cla: yes

#2272 docs: fix a typo of angular-architect example
  examples/angular_bazel_architect/README.md
Labels: cla: yes

#2275 chore: bump days before closing stale issues to 90
  .github/workflows/stale.yml
Labels: cla: yes

#2274 Fix select with condition on darwin.
  toolchains/node/BUILD.bazel
Labels: cla: yes

#2273 build: add 'fix-windows' tag due to windows flaky tests
  internal/linker/test/workspace_link/BUILD.bazel
Labels: cla: yes

#2136 feat(typescript): worker mode for ts_project
  examples/react_webpack/BUILD.bazel
  examples/react_webpack/tsconfig.json
  internal/node/node.bzl
  packages/typescript/BUILD.bazel
  packages/typescript/internal/BUILD.bazel
  packages/typescript/internal/ts_project.bzl
  packages/typescript/internal/worker/BUILD.bazel
  packages/typescript/internal/worker/worker_adapter.js
  packages/typescript/replacements.bzl
  packages/typescript/test/ts_project/worker/BUILD.bazel
  packages/typescript/test/ts_project/worker/big.ts
Labels: cla: yes

#2263 feat(node_repositories): Added auth option for downloading nodejs and…
  internal/node/node_repositories.bzl
Labels: cla: yes

#2257 fix: npm_package.pack should work in windows os
  .bazelci/presubmit.yml
  index.bzl
  internal/node/node_repositories.bzl
  internal/pkg_npm/npm_script_generator.js
  internal/pkg_npm/pkg_npm.bzl
  internal/pkg_npm/test/BUILD.bazel
  internal/pkg_npm/test/diff_pack_dir.sh
Labels: cla: yes

#2245 feat(examples): adds example for running jest with typescript
  .bazelrc
  examples/BUILD.bazel
  examples/jest/BUILD.bazel
  examples/jest/README.md
  examples/jest/jest.ts.config.js
  examples/jest/package.json
  examples/jest/ts/BUILD.bazel
  examples/jest/ts/src/BUILD.bazel
  examples/jest/ts/src/extra.ts
  examples/jest/ts/src/index.ts
  examples/jest/ts/test/BUILD.bazel
  examples/jest/ts/test/index.test.ts
  examples/jest/tsconfig.json
  examples/jest/yarn.lock
Labels: cla: no

#2278 extract function: ts_project rootDir calculation
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/rootdir/BUILD.bazel
Labels: cla: yes

#2164 fix(cypress): no longer force the use of browserify
  docs/Cypress.html
  docs/Cypress.md
  examples/cypress/package.json
  packages/cypress/BUILD.bazel
  packages/cypress/install.md
  packages/cypress/internal/cypress_repository.bzl
  packages/cypress/internal/plugins/index.template.js
  packages/cypress/internal/template.cypress_web_test.bzl
  packages/cypress/package.json
  packages/cypress/test/package.json
  packages/cypress/test/yarn.lock
Labels: cla: yes

#2282 fix: npm_package.pack on Windows should not generate undefined.tgz
  internal/node/node_repositories.bzl
Labels: cla: yes

#2284 Update nodejs versions
  internal/node/node_versions.bzl
  scripts/update-nodejs-versions.js
Labels: cla: yes

#2291 perf(cypress): pack cypress runfiles into a single tar
  examples/cypress/package.json
  packages/cypress/BUILD.bazel
  packages/cypress/internal/install-cypress.js
  packages/cypress/internal/run-cypress.js
  packages/cypress/internal/template.cypress_web_test.bzl
  packages/cypress/package.json
  packages/cypress/test/package.json
  packages/cypress/test/yarn.lock
Labels: cla: yes

#2285 chore: add GitHub Workflow to update NodeJS versions every night
  .github/workflows/update-nodejs-versions.yml
Labels: cla: yes, need: discussion

#2305 fix a link
  docs/install.md
Labels: cla: yes

#2310 fix: launcher script terminates while nodejs is still running on SIGTERM
  internal/node/launcher.sh
Labels: cla: yes

#2307 fix(typescript): don't depend on protobufjs, it's transitive
  packages/typescript/internal/ts_project.bzl
Labels: cla: yes

#2312 chore: remove old stamping
  BUILD.bazel
  internal/pkg_npm/pkg_npm.bzl
  internal/pkg_npm/test/BUILD.bazel
  packages/rollup/rollup_bundle.bzl
Labels: cla: yes

#2178 fix(examples): fix jest example on windows
  examples/jest/.bazelrc
  examples/jest/BUILD.bazel
  examples/jest/README.md
  internal/common/windows_utils.bzl
  internal/node/launcher.sh
  internal/node/test/env.spec.js
Labels: cla: yes
