Repository bazelbuild/rules_nodejs, pull requests merged in 2020-03, with the labels that each got.

#1679 fix: yarn cache path should be a string
  internal/npm_install/npm_install.bzl
Labels: bug, cla: yes

#1674 Fixes for Angular example
  examples/angular/package.json
  examples/angular_view_engine/package.json
Labels: cla: yes

#1677 fix(builtin): don't include external files when pkg_npm is in root pa…
  WORKSPACE
  internal/pkg_npm/pkg_npm.bzl
  packages/worker/BUILD.bazel
  rules_typescript.patch
Labels: cla: yes

#1681 feat(rollup): add `args` attribute to rollup_bundle rule
  packages/rollup/src/rollup_bundle.bzl
  packages/rollup/test/sourcemaps/BUILD.bazel
Labels: cla: yes, package:rollup

#1680 feat(rollup): add silent attr to rollup_bundle to support --silent flag
  packages/rollup/src/rollup_bundle.bzl
Labels: cla: yes, package:rollup

#1676 Configures detailed output to XML_OUTPUT_FILE
  package.json
  packages/jasmine/src/index.from_src.bzl
  packages/jasmine/src/index.js
  packages/jasmine/src/jasmine_node_test.bzl
  packages/jasmine/src/jasmine_runner.js
  packages/jasmine/src/package.json
  yarn.lock
Labels: cla: yes

#1683 fix(npm_install) Add /D to all cmd CD calls, this makes CD change drive as well as directory
  internal/node/node_repositories.bzl
  internal/npm_install/npm_install.bzl
Labels: cla: yes

#1688 docs: add LogiOcean as an adaptor to README.md
  README.md
Labels: cla: yes

#1685 windows_utils.bzl: Escaping \ and " before passing args to bash scrip…
  internal/common/test/BUILD.bazel
  internal/common/test/print_cmd_args.js
  internal/common/test/test_pass_cmd_args.sh
  internal/common/windows_utils.bzl
Labels: cla: yes

#1691 chore: update to bazel 2.2
  .bazelci/presubmit.yml
  .bazelversion
  index.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
Labels: cla: yes

#1699 fix(examples): fix angular examples prod serve doesn't work on windows
  examples/angular/src/BUILD.bazel
  examples/angular_view_engine/src/BUILD.bazel
Labels: cla: yes, examples, windows

#1709 chore(examples): upgrade html-insert-assets to 0.6.0
  e2e/ts_devserver/package.json
  e2e/ts_devserver/yarn.lock
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  examples/app/package.json
  examples/app/yarn.lock
Labels: cla: yes

#1717 refactor: use new label workspace_name
  internal/common/module_mappings.bzl
  internal/linker/link_node_modules.bzl
  internal/node/node.bzl
  internal/npm_install/node_module_library.bzl
  packages/typescript/src/internal/devserver/ts_devserver.bzl
Labels: cla: yes

#1716 build: remove unused parse5 third_party vendored dep
  package.json
  third_party/github.com/inikulin/parse5/BUILD.bazel
  third_party/github.com/inikulin/parse5/LICENSE
  third_party/github.com/inikulin/parse5/packages/parse5/lib/common/doctype.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/common/error-codes.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/common/foreign-content.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/common/html.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/common/unicode.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/error-reporting/mixin-base.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/error-reporting/parser-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/error-reporting/preprocessor-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/error-reporting/tokenizer-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/location-info/open-element-stack-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/location-info/parser-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/location-info/tokenizer-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/extensions/position-tracking/preprocessor-mixin.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/index.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/parser/formatting-element-list.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/parser/index.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/parser/open-element-stack.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/serializer/index.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/tokenizer/index.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/tokenizer/named-entity-data.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/tokenizer/preprocessor.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/tree-adapters/default.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/utils/merge-options.js
  third_party/github.com/inikulin/parse5/packages/parse5/lib/utils/mixin.js
Labels: cla: yes

#1707 chore: update dependency rules_pkg to v0.2.5
  WORKSPACE
  package.bzl
Labels: cla: yes

#1719 chore: add internal/node/_node_bin to .gitignore
  .gitignore
Labels: cla: yes

#1723 fix: invalid link in index
  docs/index.md
Labels: cla: yes

#1718 chore: add mrmeku as labs owner (for protobuf)
  .github/BUILD.bazel
  .github/CODEOWNERS
  packages/labs/BUILD.bazel
  scripts/update_codeowners.sh
Labels: cla: yes

#1728 fix(docs): invalid link of examples
  docs/index.md
  docs/install.md
Labels: cla: yes

#1710 feat(typescript): add ts_project rule
  examples/BUILD.bazel
  examples/react_webpack/BUILD.bazel
  examples/react_webpack/WORKSPACE
  examples/react_webpack/package.json
  examples/react_webpack/tsconfig.json
  packages/typescript/docs/install.md
  packages/typescript/src/index.bzl
  packages/typescript/src/index.docs.bzl
  packages/typescript/src/internal/BUILD.bazel
  packages/typescript/src/internal/ts_project.bzl
  packages/typescript/test/ts_project/BUILD
  packages/typescript/test/ts_project/a/BUILD.bazel
  packages/typescript/test/ts_project/a/a.ts
  packages/typescript/test/ts_project/a/tsconfig.json
  packages/typescript/test/ts_project/b/BUILD.bazel
  packages/typescript/test/ts_project/b/b.spec.ts
  packages/typescript/test/ts_project/b/b.ts
  packages/typescript/test/ts_project/b/tsconfig-test.json
  packages/typescript/test/ts_project/b/tsconfig.json
  packages/typescript/test/ts_project/c/BUILD.bazel
  packages/typescript/test/ts_project/c/c.ts
  packages/typescript/test/ts_project/c/tsconfig.json
  packages/typescript/test/ts_project/empty_intermediate/BUILD.bazel
  packages/typescript/test/ts_project/empty_intermediate/a.d.ts
  packages/typescript/test/ts_project/empty_intermediate/c.ts
  packages/typescript/test/ts_project/empty_intermediate/tsconfig-a.json
  packages/typescript/test/ts_project/empty_intermediate/tsconfig-b.json
  packages/typescript/test/ts_project/empty_intermediate/tsconfig-c.json
  packages/typescript/test/ts_project/simple/BUILD.bazel
  packages/typescript/test/ts_project/simple/index.golden.js
  packages/typescript/test/ts_project/simple/index.ts
  packages/typescript/test/ts_project/simple/tsconfig.json
  packages/typescript/test/ts_project/tsconfig-base.json
Labels: cla: yes

#1732 fix(builtin): entry point of a .tsx file is .js
  internal/node/node.bzl
Labels: cla: yes

#1734 chore(examples): remove a usage of raw tsc
  examples/app/BUILD.bazel
Labels: cla: yes

#1733 docs: update docs entry point with better quickstart content
  docs/index.md
Labels: cla: yes

#1722 Validate ts project
  packages/typescript/BUILD.bazel
  packages/typescript/replacements.bzl
  packages/typescript/src/internal/BUILD.bazel
  packages/typescript/src/internal/ts_project.bzl
  packages/typescript/src/internal/ts_project_options_validator.ts
  packages/typescript/src/package.json
  packages/typescript/test/ts_project/a/BUILD.bazel
  packages/typescript/test/ts_project/empty_intermediate/tsconfig-a.json
  packages/typescript/test/ts_project/validation/BUILD.bazel
  packages/typescript/test/ts_project/validation/a.ts
  packages/typescript/test/ts_project/validation/tsconfig.json
Labels: cla: yes

#1737 chore: rename typescript patch to its PR number
  WORKSPACE
  rules_typescript_pr_496.patch
Labels: cla: yes

#1736 refactor: removed unused code in internal/common/module_mappings.bzl
  internal/common/module_mappings.bzl
Labels: cla: yes

#1739 fix(builtin): fix for nodejs_binary entry point in bazel-out logic
  internal/node/launcher.sh
  internal/node/node.bzl
  internal/node/test/BUILD.bazel
  internal/node/test/main.ts
  internal/node/test/tsconfig.json
Labels: cla: yes

#1738 Fix typescript module mappings
  WORKSPACE
  rules_typescript_pr_494.patch
Labels: cla: yes

#1735 chore: clean up mirrored packages
  commitlint.config.js
  packages/README.md
  packages/buildifier-darwin_x64/LICENSE
  packages/buildifier-darwin_x64/package.json
  packages/buildifier-linux_x64/LICENSE
  packages/buildifier-linux_x64/package.json
  packages/buildifier-win32_x64/LICENSE
  packages/buildifier-win32_x64/package.json
  packages/buildifier/LICENSE
  packages/buildifier/buildifier.js
  packages/buildifier/package.json
  packages/buildozer-darwin_x64/LICENSE
  packages/buildozer-darwin_x64/package.json
  packages/buildozer-linux_x64/LICENSE
  packages/buildozer-linux_x64/package.json
  packages/buildozer-win32_x64/LICENSE
  packages/buildozer-win32_x64/package.json
  packages/buildozer/LICENSE
  packages/buildozer/buildozer.js
  packages/buildozer/package.json
  scripts/mirror_buildtools.sh
Labels: cla: yes

#1742 chore: add jbedard as a @bazel/rollup codeowner
  .github/BUILD.bazel
  .github/CODEOWNERS
  packages/labs/BUILD.bazel
  packages/rollup/BUILD.bazel
Labels: cla: yes

#1731 fix(docs): syntax error in example code
  docs/install.md
Labels: cla: yes, need: more info

#1743 fix(jasmine): user templated_args should be passed to jasmine after 3 internal templated_args
  packages/jasmine/src/jasmine_node_test.bzl
  packages/jasmine/test/BUILD.bazel
  packages/jasmine/test/args_test.js
Labels: cla: yes

#1687 feat(typescript): add devmode_target, devmode_module, prodmode_target & prodmode_module attributes
  packages/typescript/src/internal/build_defs.bzl
  packages/typescript/test/target_module_attributes/BUILD.bazel
  packages/typescript/test/target_module_attributes/a.ts
  packages/typescript/test/target_module_attributes/override_output_test.js
  packages/typescript/test/target_module_attributes/tsconfig-override.json
Labels: cla: yes, package:typescript

#1748 fix(typescript): pass rootDir to ts_project tsc actions
  packages/typescript/src/internal/ts_project.bzl
  packages/typescript/test/ts_project/rootdir/BUILD.bazel
  packages/typescript/test/ts_project/rootdir/subdir/a.ts
  packages/typescript/test/ts_project/rootdir/tsconfig.json
Labels: cla: yes

#1751 test: fix rollup integration tests with worker mode by removing sourcemaps from inputs
  package.json
  packages/rollup/test/integration/accept.sh
  packages/rollup/test/integration/far/a/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/BUILD.bazel
  packages/rollup/test/integration/far/a/b/c/tsconfig.json
  packages/rollup/test/integration/far/a/tsconfig.json
  packages/rollup/test/integration/foo/BUILD.bazel
  packages/rollup/test/integration/foo/tsconfig.json
  packages/rollup/test/integration/foo_a/BUILD.bazel
  packages/rollup/test/integration/foo_a/tsconfig.json
  packages/rollup/test/integration/foo_aaa/BUILD.bazel
  packages/rollup/test/integration/foo_aaa/tsconfig.json
  packages/rollup/test/integration/golden.amd.js.map.sha256_
  packages/rollup/test/integration/golden.cjs.js.map.sha256_
  packages/rollup/test/integration/golden.esm.js.map.sha256_
  packages/rollup/test/integration/golden.iife.js.map.sha256_
  packages/rollup/test/integration/golden.system.js.map.sha256_
  packages/rollup/test/integration/golden.umd.js.map.sha256_
  yarn.lock
Labels: cla: yes

#1755 chore: update to Bazel 3.0 rc
  .bazelci/presubmit.yml
  .bazelversion
  index.bzl
Labels: cla: yes

#1756 fix(typescript): include extended tsconfigs in _TsConfigInfo
  packages/typescript/src/internal/ts_project.bzl
  packages/typescript/test/ts_project/a/BUILD.bazel
  packages/typescript/test/ts_project/a/tsconfig-extended.json
  packages/typescript/test/ts_project/a/tsconfig.json
Labels: cla: yes

#1766 fix(docs): `yarn_urls` should be `string_list`, not `string`
  internal/node/node_repositories.bzl
Labels: cla: yes

#1767 chore: add yarn 1.22.4 to node_repositories
  internal/node/node_repositories.bzl
Labels: cla: yes

#1758 feat(example): add support for server side rendering with universal
  examples/angular/README.md
  examples/angular/package.json
  examples/angular/src/BUILD.bazel
  examples/angular/src/app/BUILD.bazel
  examples/angular/src/app/app.module.ts
  examples/angular/src/app/app.server.module.ts
  examples/angular/src/server.ts
  examples/angular/src/tsconfig.server.json
  examples/angular/yarn.lock
Labels: cla: yes

#1747 chore: rely less on the index.from_src pattern
  examples/nestjs/src/BUILD.bazel
  internal/common/test/BUILD.bazel
  internal/linker/test/BUILD.bazel
  internal/linker/test/integration/absolute_import/BUILD.bazel
  internal/linker/test/integration/static_linked_pkg/BUILD.bazel
  internal/node/node.bzl
  internal/npm_install/test/package/BUILD.bazel
  internal/pkg_npm/test/BUILD.bazel
  internal/pkg_npm/test/linking/feb/BUILD.bazel
  internal/pkg_npm/test/linking/fez/BUILD.bazel
  internal/pkg_npm/test/vendored_external/BUILD.bazel
  internal/pkg_web/test/BUILD.bazel
  internal/pkg_web/test2/BUILD.bazel
  packages/karma/src/BUILD.bazel
  packages/karma/test/karma_typescript/BUILD.bazel
  packages/karma/test/stack_trace/BUILD.bazel
  packages/karma/test/stack_trace/test_folder/BUILD.bazel
  packages/labs/test/grpc_web/BUILD.bazel
  packages/labs/test/grpc_web/proto/BUILD.bazel
  packages/labs/test/grpc_web/proto/common/BUILD.bazel
  packages/labs/test/protobufjs/BUILD.bazel
  packages/protractor/src/BUILD.bazel
  packages/protractor/test/protractor-2/BUILD.bazel
  packages/protractor/test/protractor-utils/BUILD.bazel
  packages/protractor/test/protractor/BUILD.bazel
  packages/terser/BUILD.bazel
  packages/terser/src/BUILD.bazel
  packages/terser/src/index.from_src.bzl
  packages/terser/src/terser_minified.bzl
  packages/terser/test/args/BUILD.bazel
  packages/terser/test/debug/BUILD.bazel
  packages/terser/test/directory_input/BUILD.bazel
  packages/terser/test/inline_sourcemap/BUILD.bazel
  packages/terser/test/sourcemap/BUILD.bazel
  packages/terser/test/user_config/BUILD.bazel
  packages/typescript/replacements.bzl
  packages/typescript/src/index.from_src.bzl
  packages/typescript/src/internal/build_defs.bzl
  packages/typescript/test/absolute_imports/BUILD.bazel
  packages/typescript/test/errorchecks/BUILD.bazel
  packages/typescript/test/foobar/BUILD.bazel
  packages/typescript/test/generated_ts/BUILD.bazel
  packages/typescript/test/googmodule/BUILD.bazel
  packages/typescript/test/lit_plugin/BUILD.bazel
  packages/typescript/test/reference_types_directive/BUILD.bazel
  packages/typescript/test/some_library/BUILD.bazel
  packages/typescript/test/some_module/BUILD.bazel
  packages/typescript/test/strict_deps/BUILD
  packages/typescript/test/target_module_attributes/BUILD.bazel
  packages/typescript/test/tsconfig_extends/BUILD.bazel
Labels: cla: yes

#1765 feat(typescript): wire up use_angular_plugin attribute
  examples/angular/BUILD.bazel
  examples/angular/README.md
  examples/angular/package.json
  examples/angular/src/BUILD.bazel
  examples/angular/src/app/BUILD.bazel
  examples/angular/src/app/hello-world/BUILD.bazel
  examples/angular/src/app/home/BUILD.bazel
  examples/angular/src/app/todos/BUILD.bazel
  examples/angular/src/shared/material/BUILD.bazel
  examples/angular/yarn.lock
  package.json
  packages/typescript/src/internal/build_defs.bzl
  packages/typescript/test/angular_plugin/compiled_output/BUILD.bazel
  packages/typescript/test/angular_plugin/compiled_output/comp.ng.html
  packages/typescript/test/angular_plugin/compiled_output/component.ts
  packages/typescript/test/angular_plugin/compiled_output/spec.js
  packages/typescript/test/angular_plugin/compiled_output/tsconfig.json
  packages/typescript/test/angular_plugin/diagnostic/BUILD.bazel
  packages/typescript/test/angular_plugin/diagnostic/comp.ng.html
  packages/typescript/test/angular_plugin/diagnostic/component.ts
  packages/typescript/test/angular_plugin/diagnostic/tsconfig.json
  yarn.lock
Labels: cla: yes
