Repository bazelbuild/rules_nodejs, pull requests merged in 2020-06, with the labels that each got.

#1935 ci: re-enable Angular architect test on Windows
  examples/BUILD.bazel
Labels: cla: yes

#1933 fix(terser): allow fallback binary resolution
  packages/terser/index.js
Labels: cla: yes

#1936 Add linux arm64 support
  docs/install.md
  internal/common/os_name.bzl
  internal/node/launcher.sh
  internal/node/node_repositories.bzl
  internal/node/test/nodejs_toolchain_test.bzl
  packages/typescript/devserver/BUILD.bazel
  toolchains/node/BUILD.bazel
Labels: cla: yes

#1925 chore: rename a npm dependency to demonstrate that it doesn't need to…
  examples/webapp/BUILD.bazel
  examples/webapp/WORKSPACE
  examples/webapp/differential_loading.bzl
Labels: cla: yes

#1464 refactor: remove install_source_map_support from nodejs_binary since it is vendored in
  examples/angular/tools/angular_prerender.bzl
  internal/bazel_integration_test/BUILD.bazel
  internal/node/node.bzl
  internal/node/require_patch.js
  internal/npm_install/BUILD.bazel
  internal/npm_install/generate_build_file.ts
  internal/npm_install/index.js
  internal/npm_install/test/BUILD.bazel
  internal/npm_install/test/golden/@gregmagolan/test-a/bin/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-a/index.bzl.golden
  internal/npm_install/test/golden/jasmine/bin/BUILD.bazel.golden
  internal/npm_install/test/golden/jasmine/index.bzl.golden
  internal/pkg_npm/BUILD.bazel
  internal/pkg_web/BUILD.bazel
  packages/karma/BUILD.bazel
  packages/labs/protobufjs/BUILD.bazel
Labels: cla: yes

#1944 feat(typescript): include label in the ts_project progress message
  packages/typescript/internal/ts_project.bzl
Labels: cla: yes

#1947 feat(typescript): add outdir to ts_project
  packages/typescript/internal/ts_project.bzl
  packages/typescript/test/ts_project/outdir/BUILD.bazel
  packages/typescript/test/ts_project/outdir/a.golden.cjs
  packages/typescript/test/ts_project/outdir/a.golden.js
  packages/typescript/test/ts_project/outdir/a.ts
  packages/typescript/test/ts_project/outdir/tsconfig.json
Labels: cla: yes

#1945 chore: upgrade Bazel core packages
  examples/parcel/parcel.bzl
  internal/common/copy_to_bin.bzl
  internal/common/params_file.bzl
  internal/coverage/BUILD.bazel
  internal/js_library/js_library.bzl
  internal/linker/test/integration/rule.bzl
  internal/node/npm_package_bin.bzl
  internal/npm_install/node_module_library.bzl
  internal/npm_install/npm_install.bzl
  internal/npm_install/npm_umd_bundle.bzl
  internal/pkg_npm/pkg_npm.bzl
  internal/pkg_web/pkg_web.bzl
  internal/providers/linkable_package_info.bzl
  internal/providers/node_runtime_deps_info.bzl
  package.json
  packages/karma/karma_web_test.bzl
  packages/labs/protobufjs/ts_proto_library.bzl
  packages/protractor/protractor_web_test.bzl
  packages/rollup/rollup_bundle.bzl
  packages/terser/terser_minified.bzl
  packages/typescript/internal/build_defs.bzl
  packages/typescript/internal/devserver/ts_devserver.bzl
  packages/typescript/internal/ts_config.bzl
  packages/typescript/internal/ts_project.bzl
  yarn.lock
Labels: cla: yes

#1948 ci: fix in-flight semantic breakage
  packages/typescript/test/ts_project/outdir/BUILD.bazel
Labels: cla: yes

#1942 fix(labs): make grpc service files tree shakable
  examples/protocol_buffers/app.e2e-spec.ts
  examples/protocol_buffers/app.ts
  examples/protocol_buffers/car.proto
  examples/protocol_buffers/package.json
  package.json
  packages/labs/grpc_web/change_import_style.js
  yarn.lock
Labels: cla: yes

#1932 chore(examples): upgrade angular example to angular 10.0.0-rc
  examples/angular/package.json
  examples/angular/patches/@angular+compiler-cli+10.0.0-rc.6.patch
  examples/angular/yarn.lock
Labels: cla: yes

#1440 refactor: always link
  e2e/BUILD.bazel
  e2e/node_loader_no_preserve_symlinks/BUILD.bazel
  e2e/packages/npm1/package-lock.json
  e2e/packages/npm2/package-lock.json
  e2e/packages/yarn1/yarn.lock
  e2e/packages/yarn2/yarn.lock
  examples/angular/tools/angular_prerender.bzl
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/node/launcher.sh
  packages/labs/protobufjs/BUILD.bazel
  packages/node-patches/BUILD.bazel
Labels: cla: yes

#1703 feat(jasmine): make deps peerDeps
  e2e/bazel_managed_deps/package.json
  e2e/bazel_managed_deps/yarn.lock
  e2e/jasmine/package.json
  e2e/jasmine/yarn.lock
  e2e/typescript/package.json
  e2e/typescript/yarn.lock
  examples/kotlin/package.json
  examples/nestjs/package.json
  examples/nestjs/yarn.lock
  examples/parcel/package-lock.json
  examples/vendored_node/package.json
  examples/vendored_node_and_yarn/package.json
  examples/vendored_node_and_yarn/yarn.lock
  packages/jasmine/package.json
Labels: cla: yes, help wanted

#1843 feat(builtin): add JSModuleInfo provider
  internal/js_library/js_library.bzl
  internal/node/node.bzl
  internal/node/npm_package_bin.bzl
  internal/npm_install/node_module_library.bzl
  internal/pkg_npm/pkg_npm.bzl
  internal/providers/js_providers.bzl
  packages/jasmine/jasmine_node_test.bzl
  packages/karma/karma_web_test.bzl
  packages/labs/grpc_web/ts_proto_library.bzl
  packages/labs/protobufjs/ts_proto_library.bzl
  packages/protractor/protractor_web_test.bzl
  packages/rollup/rollup_bundle.bzl
  packages/terser/terser_minified.bzl
  packages/terser/test/js_srcs/BUILD.bazel
  packages/terser/test/js_srcs/produces_js_as_defaultinfo.bzl
  packages/terser/test/js_srcs/src1.js
  packages/terser/test/js_srcs/src1b.js
  packages/terser/test/js_srcs/src2.js
  packages/terser/test/js_srcs/terser_spec.js
  packages/typescript/internal/build_defs.bzl
  packages/typescript/internal/ts_project.bzl
  providers.bzl
Labels: cla: yes

#1972 chore: update lock files for 2.0.0-rc.0 release
  e2e/bazel_managed_deps/package.json
  e2e/bazel_managed_deps/yarn.lock
  e2e/jasmine/package.json
  e2e/jasmine/yarn.lock
  e2e/ts_devserver/package.json
  e2e/ts_devserver/yarn.lock
  e2e/typescript/package.json
  e2e/typescript/yarn.lock
  e2e/webapp/package.json
  e2e/webapp/yarn.lock
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_bazel_architect/package.json
  examples/angular_bazel_architect/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  examples/app/package.json
  examples/app/yarn.lock
  examples/kotlin/package-lock.json
  examples/kotlin/package.json
  examples/nestjs/package.json
  examples/nestjs/yarn.lock
  examples/protocol_buffers/package.json
  examples/protocol_buffers/yarn.lock
  examples/react_webpack/package.json
  examples/react_webpack/yarn.lock
  examples/vendored_node/package-lock.json
  examples/vendored_node/package.json
  examples/vendored_node_and_yarn/package.json
  examples/vendored_node_and_yarn/yarn.lock
  examples/web_testing/package.json
  examples/web_testing/yarn.lock
  examples/webapp/package.json
  examples/webapp/yarn.lock
  examples/worker/package.json
  examples/worker/yarn.lock
  scripts/update_nested_lock_files.sh
Labels: cla: yes

#1975 fix: allow multiple run_node calls to be made from the same rule context
  internal/linker/link_node_modules.bzl
  internal/providers/node_runtime_deps_info.bzl
  internal/providers/test/BUILD.bazel
  internal/providers/test/_run_node_out.txt
  internal/providers/test/js-write-file.js
  internal/providers/test/run_node_test.bzl
Labels: 2.0 Release Blocker, cla: yes

#1985 chore(examples): upgrade angular example to 10.0.2 and remove ngtsc patch
  examples/angular/package.json
  examples/angular/patches/@angular+compiler-cli+10.0.0-rc.6.patch
  examples/angular/yarn.lock
Labels: cla: yes

#1983 chore(docs): add testimonial from Allocadia
  README.md
Labels: cla: yes

#1981 fix(typescript): Exclude .json from _out_paths
  packages/typescript/internal/ts_project.bzl
Labels: cla: yes
