Repository bazelbuild/rules_nodejs, pull requests merged in 2020-01, with the labels that each got.

#1518 Angular deps update
  examples/angular/.bazelrc
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-rc.7.patch
  examples/angular/src/BUILD.bazel
  examples/angular/src/app/BUILD.bazel
  examples/angular/src/app/hello-world/BUILD.bazel
  examples/angular/src/app/hello-world/hello-world.component.spec.ts
  examples/angular/src/app/todos/BUILD.bazel
  examples/angular/src/shared/material/BUILD.bazel
  examples/angular/src/tsconfig.json
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/patches/@angular+bazel+9.0.0-rc.7.patch
  examples/angular_view_engine/yarn.lock
Labels: cla: yes

#1517 feat(builtin): allow patching require in bootstrap scripts
  e2e/jasmine/BUILD.bazel
  e2e/jasmine/jasmine_shared_env_bootstrap.js
  internal/golden_file_test/bin.js
  internal/linker/BUILD.bazel
  internal/linker/index.js
  internal/linker/link_node_modules.ts
  internal/linker/runfiles_helper.js
  internal/node/node.bzl
  internal/node/node_launcher.sh
  internal/npm_install/test/check.js
  packages/jasmine/src/jasmine_runner.js
Labels: cla: yes, package:builtin

#1528 Examples nestjs test
  examples/BUILD.bazel
  examples/nestjs/package.json
  examples/nestjs/src/BUILD.bazel
  examples/nestjs/src/app.controller.ts
  examples/nestjs/src/main.spec.ts
  examples/nestjs/src/main.ts
  examples/nestjs/yarn.lock
Labels: cla: yes

#1531 refactor: upgrade to runfiles.bash initialization v2
  internal/common/test/copy_to_bin_tests.sh
  internal/linker/test/integration/run_program.sh
  internal/node/node_launcher.sh
  internal/npm_install/test/bazel_bin_test.sh
  packages/typescript/src/internal/devserver/launcher_template.sh
  packages/typescript/test/devmode_consumer/devmode_consumer_test.sh
  packages/typescript/test/es6_consumer/es6_output_test.sh
  packages/typescript/test/some_module/module_load_test.sh
Labels: cla: yes

#1534 build: update to latest rules_typescript commit and remove patch
  WORKSPACE
  examples/user_managed_deps/WORKSPACE
  examples/user_managed_deps/rules_typescript.patch
  rules_typescript.patch
Labels: cla: yes, dependencies

#1515 feat(examples): add nodejs_binary cluster example
  examples/nestjs/package.json
  examples/nestjs/src/BUILD.bazel
  examples/nestjs/src/main.spec.ts
  examples/nestjs/src/main.ts
  examples/nestjs/yarn.lock
Labels: cla: yes, need: more info

#1543 refactor: use runfiles = require(process.env['BAZEL_NODE_RUNFILES_HEL…
  examples/closure/test.js
  internal/node/test/npm_package_bin.spec.js
  internal/pkg_npm/test/pkg_npm.spec.js
  packages/rollup/test/code_splitting/spec.js
  packages/rollup/test/multiple_entry_points/spec.js
  packages/rollup/test/sourcemaps/spec.js
  packages/terser/test/directory_input/spec.js
  packages/terser/test/inline_sourcemap/spec.js
  packages/terser/test/sourcemap/directory_spec.js
  packages/typescript/test/googmodule/googmodule_output_test.js
Labels: cla: yes

#1538 presubmit.yml: Set skip_use_bazel_version_for_test: true
  .bazelci/presubmit.yml
Labels: cla: yes

#1550 refactor: use runfiles bash helper v2 in karma, protractor & bazel_integration_test rules
  internal/bazel_integration_test/bazel_integration_test.bzl
  packages/karma/src/karma_web_test.bzl
  packages/protractor/src/protractor_web_test.bzl
Labels: cla: yes

#1552 chore: remove webpack_bundle rule from labs
  .bazelrc
  e2e/BUILD.bazel
  e2e/webpack/.bazelignore
  e2e/webpack/.bazelrc
  e2e/webpack/BUILD.bazel
  e2e/webpack/WORKSPACE
  e2e/webpack/index.js
  e2e/webpack/package.json
  e2e/webpack/strings.en.js
  e2e/webpack/test.js
  e2e/webpack/yarn.lock
  package.json
  packages/labs/BUILD.bazel
  packages/labs/src/BUILD.bazel
  packages/labs/src/index.bzl
  packages/labs/src/package.json
  packages/labs/src/webpack/BUILD.bazel
  packages/labs/src/webpack/README.md
  packages/labs/src/webpack/cli.ts
  packages/labs/src/webpack/webpack_bundle.bzl
  packages/labs/test/webpack/BUILD.bazel
  packages/labs/test/webpack/bundle.spec.ts
  packages/labs/test/webpack/index.js
  packages/labs/test/webpack/strings.js
Labels: cla: yes

#1557 Update README.md to add our organization
  README.md
Labels: cla: yes

#1564 Do not error with unbound variable when running karma web test with `bazel run`
  packages/karma/src/karma_web_test.bzl
Labels: cla: yes

#1570 chore: add protoc-gen-ts to open-source repositories list.
  README.md
Labels: cla: yes

#1571 build: update angular examples to angular 9.0.0-rc.10
  examples/angular/package.json
  examples/angular/patches/@angular+bazel+9.0.0-rc.7.patch
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/patches/@angular+bazel+9.0.0-rc.7.patch
  examples/angular_view_engine/yarn.lock
  yarn.lock
Labels: cla: yes

#1569 fix(builtin): set cwd before running yarn for yarn_install
  internal/node/node_repositories.bzl
  internal/npm_install/npm_install.bzl
Labels: bug, cla: yes, package:builtin

#1581 fix: yarn_install failure if yarn is a dependency
  internal/npm_install/npm_install.bzl
  package.json
  yarn.lock
Labels: bug, cla: yes, package:builtin

#1578 fix: osx hide-bazel-files issue with fsevents
  packages/hide-bazel-files/index.js
Labels: bug, cla: yes

#1586 fixes bazelbuild/rules_nodejs#1567 Recursively copy files from subdir…
  internal/pkg_npm/packager.js
  internal/pkg_npm/test/BUILD.bazel
  internal/pkg_npm/test/pkg_npm.spec.js
Labels: cla: yes

#1506 feat: enable test file crawling for jest example
  .vscode/settings.json
  examples/jest/BUILD.bazel
  examples/jest/WORKSPACE
  examples/jest/jest.bzl
  examples/jest/package.json
  examples/jest/patches/jest-haste-map+24.9.0.patch
  examples/jest/yarn.lock
Labels: cla: yes

#1558 Replace grep with bash's regex operator
  internal/node/node_patches.js
  packages/node-patches/src/subprocess.ts
Labels: cla: yes

#1588 fix: unset YARN_IGNORE_PATH in yarn_install before calling yarn
  internal/npm_install/npm_install.bzl
Labels: bug, cla: yes, package:builtin

#1597 fix(builtin): fix logic error in linker conflict resolution
  internal/linker/link_node_modules.bzl
  internal/linker/test/integration/BUILD.bazel
Labels: bug, cla: yes, package:builtin

#1591 fix(builtin): strip leading v prefix from stamp
  internal/pkg_npm/packager.js
Labels: cla: yes
