Repository bazelbuild/rules_nodejs, pull requests merged in 2020-02, with the labels that each got.

#1600 feat(builtin): generate `@npm//foo__all_files` filegroup that includes all files in the npm package
  WORKSPACE
  internal/node/node.bzl
  internal/npm_install/generate_build_file.js
  internal/npm_install/generate_build_file.ts
  internal/npm_install/test/BUILD.bazel
  internal/npm_install/test/golden/@angular/core/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-a/BUILD.bazel.golden
  internal/npm_install/test/golden/@gregmagolan/test-b/BUILD.bazel.golden
  internal/npm_install/test/golden/BUILD.bazel.golden
  internal/npm_install/test/golden/ajv/BUILD.bazel.golden
  internal/npm_install/test/golden/jasmine/BUILD.bazel.golden
  internal/npm_install/test/golden/rxjs/BUILD.bazel.golden
  internal/npm_install/test/golden/unidiff/BUILD.bazel.golden
  internal/npm_install/test/golden/zone.js/BUILD.bazel.golden
  package.json
  tools/fine_grained_goldens/package.json
  tools/fine_grained_goldens/yarn.lock
  yarn.lock
Labels: cla: yes, package:builtin

#1596 feat(builtin): add environment attribute to yarn_install & npm_install
  WORKSPACE
  internal/npm_install/npm_install.bzl
  internal/npm_install/test/postinstall.js
  package.json
  tools/fine_grained_deps_npm/package.json
  tools/fine_grained_deps_yarn/package.json
Labels: cla: yes, package:builtin

#1603 chore: support Bazelisk and stop using @bazel/bazel
  .bazelversion
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  docs/install.md
  examples/BUILD.bazel
  examples/angular/README.md
  examples/angular/WORKSPACE
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_bazel_architect/package.json
  examples/angular_bazel_architect/yarn.lock
  examples/angular_view_engine/WORKSPACE
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  examples/nestjs/package.json
  examples/nestjs/yarn.lock
  examples/react_webpack/package.json
  examples/react_webpack/yarn.lock
  index.bzl
  internal/BUILD.bazel
  internal/check_bazel_version.js
  internal/common/check_bazel_version.bzl
  package.json
  packages/create/BUILD.bazel
  packages/create/README.md
  packages/create/index.js
  packages/create/test.js
  packages/typescript/src/internal/ts_repositories.bzl
  yarn.lock
Labels: cla: yes

#1594 feat(examples): add protractor angular architect
  .circleci/config.yml
  examples/angular_bazel_architect/BUILD.bazel
  examples/angular_bazel_architect/e2e/protractor.conf.js
Labels: cla: yes, examples

#1607 build: fix in-flight conflict with angular_bazel_architect example
  examples/BUILD.bazel
  examples/angular_bazel_architect/package.json
  examples/angular_bazel_architect/yarn.lock
Labels: bug, cla: yes

#1608 chore: remove @bazel/bazel package
  packages/bazel-darwin_x64/LICENSE
  packages/bazel-darwin_x64/package.json
  packages/bazel-linux_x64/LICENSE
  packages/bazel-linux_x64/package.json
  packages/bazel-win32_x64/LICENSE
  packages/bazel-win32_x64/package.json
  packages/bazel/LICENSE
  packages/bazel/index.js
  packages/bazel/package.json
  scripts/mirror_bazel.sh
Labels: cla: yes

#1611 Update install.md for "noEmit" compiler flag
  packages/typescript/docs/install.md
Labels: cla: yes

#1605 fix: angular example ts_scripts path in Windows
  examples/angular/src/BUILD.bazel
  examples/angular_view_engine/src/BUILD.bazel
Labels: cla: yes, examples

#1593 change ts_proto_library to default es5 wrapping
  WORKSPACE
  packages/labs/src/protobufjs/ts_proto_library.bzl
  packages/labs/test/protobufjs/BUILD.bazel
  packages/labs/test/protobufjs/test.proto
  packages/labs/test/protobufjs/test.ts
Labels: cla: yes

#1610 fix: html script injection is broken on windows
  e2e/ts_devserver/package.json
  e2e/ts_devserver/yarn.lock
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_view_engine/package.json
  examples/angular_view_engine/yarn.lock
  examples/app/package.json
  examples/app/yarn.lock
Labels: cla: yes, examples

#1620 docs(examples): update header example link
  examples/angular/src/index.html
Labels: cla: yes

#1623 chore: remove compat flags for rules_go and bazel 0.27
  .bazelrc
Labels: cla: yes

#1622 chore: remove local_resources flag
  .bazelci/presubmit.yml
  .circleci/bazel.rc
  .circleci/config.yml
  DEVELOPING.md
  package.json
Labels: cla: yes

#1625 chore(examples): upgrade rules_nodejs and angular
  examples/angular/package.json
  examples/angular/yarn.lock
  examples/angular_bazel_architect/WORKSPACE
  examples/angular_bazel_architect/package.json
  examples/angular_bazel_architect/patches/@angular-devkit+architect-cli+0.900.1.patch
  examples/angular_bazel_architect/yarn.lock
Labels: cla: yes, examples

#1626 fix: expand_variables helper should handle external labels
  internal/common/expand_variables.bzl
Labels: bug, cla: yes

#1629 build: update to rules_sass 1.25.0
  examples/angular/WORKSPACE
  examples/angular_view_engine/WORKSPACE
  package.bzl
Labels: cla: yes

#1628 build: add bazel-out to .bazelignore
  .bazelignore
Labels: bug, cla: yes

#1631 fix: logic error in expand_variables
  internal/common/expand_variables.bzl
  internal/node/npm_package_bin.bzl
Labels: bug, cla: yes, package:builtin

#1615 feat(examples): add serve to angular architect
  examples/angular_bazel_architect/BUILD.bazel
Labels: cla: yes

#1636 fix(builtin): use posix paths in assembler
  internal/pkg_web/BUILD.bazel
  internal/pkg_web/assembler.js
Labels: cla: yes, package:builtin, windows

#1634 fix: ensure BAZEL_NODE_RUNFILES_HELPER & BAZEL_NODE_PATCH_REQUIRE are absolute
  internal/node/launcher.sh
  internal/node/test/BUILD.bazel
  internal/node/test/test_runfiles_helper.golden
  internal/node/test/test_runfiles_helper.js
Labels: bug, cla: yes

#1650 fix: remove empty arguments from launcher
  internal/node/launcher.sh
  internal/node/test/BUILD.bazel
  internal/node/test/empty_args_fail.js
Labels: bug, cla: yes

#1639 fix(examples): add fixes to angular architect
  examples/angular_bazel_architect/BUILD.bazel
  examples/angular_bazel_architect/angular.json
  examples/angular_bazel_architect/package.json
Labels: cla: yes

#1653 feat(@bazel/jasmine): update dependencies to jasmine v3.5.0
  packages/jasmine/src/package.json
Labels: cla: yes

#1654 fix(create): use latest typescript
  packages/create/index.js
Labels: cla: yes

#1668 chore: update Bazel to 2.1.1
  .bazelci/presubmit.yml
  .bazelversion
  index.bzl
Labels: cla: yes

#1660 docs(talks): add new talk slides and video link
  examples/angular/src/index.html
Labels: cla: yes

#1630 feat(typescript): add plugin support for type-checking lit-element
  WORKSPACE
  internal/linker/index.js
  package.json
  packages/typescript/src/internal/BUILD.bazel
  packages/typescript/src/internal/build_defs.bzl
  packages/typescript/test/lit_plugin/BUILD.bazel
  packages/typescript/test/lit_plugin/bad.ts
  packages/typescript/test/lit_plugin/declared_element.d.ts
  packages/typescript/test/lit_plugin/elements.ts
  packages/typescript/test/lit_plugin/tsconfig.json
  packages/worker/BUILD.bazel
  yarn.lock
Labels: cla: yes

#1659 chore: switch to rules_pkg
  .bazelrc
  BUILD.bazel
  index.bzl
  package.bzl
  tools/defaults.bzl
Labels: cla: yes
