Repository bazelbuild/rules_nodejs, pull requests merged in 2021-08, with the labels that each got.

#2844 chore: enable tests on buildkite rbe_ubuntu1604
  .bazelci/presubmit.yml
  internal/pkg_npm/test/BUILD.bazel
  packages/concatjs/web_test/test/karma/BUILD.bazel
Labels: cla: yes

#2847 Update NodeJS Versions
  internal/node/node_versions.bzl
Labels: cla: yes

#2837 Don't use false as a no-error value
  internal/node/node_patches.js
  packages/node-patches/src/fs.ts
Labels: cla: yes

#2846 chore: enable tests on buildkite rbe_ubuntu1604
  .bazelci/presubmit.yml
  internal/pkg_npm/test/BUILD.bazel
  packages/concatjs/web_test/test/karma/BUILD.bazel
Labels: cla: yes

#2745 fix ts_proto_library handling of external proto_library
  packages/labs/grpc_web/change_import_style.js
  packages/labs/grpc_web/ts_proto_library.bzl
Labels: cla: yes

#2855 Update NodeJS Versions
  internal/node/node_versions.bzl
Labels: cla: yes

#2854 chore: remove version checking from @bazel/worker
  packages/worker/BUILD.bazel
  packages/worker/package.json
Labels: cla: yes

#2851 fix(typescript): document tsc_test for typecheck-only
  packages/typescript/index.docs.bzl
  packages/typescript/test/tsc_test/BUILD.bazel
  packages/typescript/test/tsc_test/check_me.ts
Labels: cla: yes

#2858 chore(esbuild): update versions used
  packages/esbuild/esbuild_packages.bzl
  packages/esbuild/toolchain/package-lock.json
  packages/esbuild/toolchain/package.json
Labels: cla: yes

#2859 chore: suppress //internal/npm_install/test:test_yarn_directory_artif…
  internal/npm_install/test/BUILD.bazel
  packages/typescript/test/tsc_test/BUILD.bazel
  packages/typescript/test/tsc_test/check_me.ts
Labels: cla: yes

#2853 fix(builtin): correctly calculate pkg._directDependency when a mapped node_module is used
  internal/npm_install/generate_build_file.ts
  internal/npm_install/index.js
Labels: cla: yes

#2860 docs(typescript): update typescript docs
  docs/TypeScript.md
Labels: cla: yes

#2525 fix: remove current directory prefix when running from execroot
  internal/node/launcher.sh
Labels: cla: yes

#2840 feat(esbuild): add support for plugins via supplying a configuration file
  docs/esbuild.md
  package.json
  packages/esbuild/BUILD.bazel
  packages/esbuild/esbuild.bzl
  packages/esbuild/esbuild_config.bzl
  packages/esbuild/index.bzl
  packages/esbuild/index.docs.bzl
  packages/esbuild/launcher.js
  packages/esbuild/test/plugins/BUILD.bazel
  packages/esbuild/test/plugins/esbuild.config.mjs
  packages/esbuild/test/plugins/logo.svg
  packages/esbuild/test/plugins/main.js
  packages/esbuild/test/plugins/out.golden.txt
  packages/esbuild/test/plugins/txt-array-plugin.js
  packages/esbuild/test/plugins/words.txt
  yarn.lock
Labels: cla: yes

#2861 chore: fix type assertions when using newer node typings
  packages/node-patches/test/fs/opendir.ts
  packages/node-patches/test/fs/readdir.ts
  third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/worker.ts
Labels: cla: yes

#2862 chore: update defaults to latest node/yarn versions
  docs/Built-ins.md
  internal/node/node_repositories.bzl
Labels: cla: yes

#2865 chore(esbuild): remove todo comment that no longer applies
  packages/esbuild/esbuild.bzl
Labels: cla: yes

#2870 chore: disable two tests that are timing out on buildkite
  examples/BUILD.bazel
Labels: cla: yes

#2871 Update NodeJS Versions
  internal/node/node_versions.bzl
Labels: cla: yes

#2869 Linux ppc64le support
  docs/install.md
  internal/common/os_name.bzl
  internal/node/launcher.sh
  internal/node/node_repositories.bzl
  internal/node/node_versions.bzl
  internal/node/test/nodejs_toolchain_test.bzl
  packages/concatjs/devserver/BUILD.bazel
  scripts/update-nodejs-versions.js
  toolchains/node/BUILD.bazel
Labels: cla: no

#2876 fix(cypress): don't eager-fetch the npm repository just to get the cy…
  BUILD.bazel
  docs/Cypress.md
  examples/cypress/WORKSPACE
  packages/cypress/BUILD.bazel
  packages/cypress/index.bzl
  packages/cypress/internal/BUILD.bazel
  packages/cypress/internal/cypress_web_test.bzl
  toolchains/cypress/BUILD.bazel
  toolchains/cypress/cypress_repositories.bzl
  toolchains/cypress/cypress_toolchain.bzl
Labels: cla: yes

#2877 docs: stardoc for toolchains
  BUILD.bazel
  docs/BUILD.bazel
  docs/Toolchains.md
  internal/node/BUILD.bazel
  toolchains/BUILD.bazel
  toolchains/cypress/BUILD.bazel
  toolchains/esbuild/BUILD.bazel
  toolchains/index.for_docs.bzl
Labels: cla: yes

#2881 fix: update usages of `ExternalNpmPackageInfo.path` to be safe and default to empty string
  internal/linker/link_node_modules.bzl
  internal/linker/test/default_path/BUILD.bazel
  internal/linker/test/default_path/custom_external_npm_package_info.bzl
  internal/linker/test/default_path/default_path.js
  internal/linker/test/default_path/golden.txt
  internal/node/node.bzl
  internal/providers/external_npm_package_info.bzl
  internal/providers/node_runtime_deps_info.bzl
Labels: cla: yes

#2882 fix(cypress): add js files from JSModuleInfo to plugin wrapper sources if available
  packages/cypress/internal/cypress_web_test.bzl
  packages/cypress/test/BUILD.bazel
  packages/cypress/test/lib_plugin.js
Labels: cla: yes

#2880 fix: update Skylib hash
  packages/create/index.js
Labels: cla: yes

#2891 build: add github action to update esbuild versions
  .github/workflows/update-esbuild-versions.yml
Labels: cla: yes

#2902 fix: update `tsutils` to version `3.21.0`
  package.json
  packages/concatjs/package.json
  packages/typescript/package.json
  third_party/github.com/bazelbuild/rules_typescript/internal/tsc_wrapped/package.json
  third_party/github.com/bazelbuild/rules_typescript/package.json
  yarn.lock
Labels: cla: yes, dependencies
